name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - main

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps: # 步骤
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
          #      - name: run deploy.sh # 步骤3 （同时部署到github和coding）
          #        env: # 设置环境变量
          #          GITHUB_TOKEN: ${{ secrets.my_su_token }} # toKen私密变量
          #        run: npm install && npm run deploy

      - name: pull-request
          uses: repo-sync/pull-request@v2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Sync files # 步骤3 （只提交到github可以使用这个步骤）
#        uses: SamKirkland/FTP-Deploy-Action@4.1.0 # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
#        with: # 设置环境变量
#          server: 118.25.22.194 # 要部署的文件夹所在的分支.
#          password: ${{ secrets.ftp_password }} # toKen私密变量
#          username: ftpxiaosu # 部署到的分支
#          local-dir: ./docs/ # 要部署的文件夹.
#          server-dir: ./opt/ # 要部署的文件夹.

#      - name: FTP Deploy
#        uses: SamKirkland/FTP-Deploy-Action@2.0.0
#        env:
#          FTP_SERVER: 118.25.22.194
#          FTP_USERNAME: ftpxiaosu
#          FTP_PASSWORD: ${{ secrets.ftp_password }}
#          LOCAL_DIR: docs
#          REMOTE_DIR: /home/ftpxiaosu
#          ARGS: --delete --transfer-all --exclude=logreport --verbose

#      - name: Build and Deploy # 步骤3 （只提交到github可以使用这个步骤）
#        uses: JamesIves/github-pages-deploy-action@4.1.1 # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
#        env: # 设置环境变量
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
#          BASE_BRANCH: main # 要部署的文件夹所在的分支.
#          BRANCH: gh-pages # 部署到的分支
#          FOLDER: docs # 要部署的文件夹.
#          BUILD_SCRIPT: cd docs && echo 'test6.xiaolongsu.cn' > CNAME && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）